// <auto-generated />
using GambaNet.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GambaNet_Web.Migrations
{
    [DbContext(typeof(GambaNetDbContext))]
    [Migration("20241030140803_mysql_1.0.1_seeding_transactiontype_games")]
    partial class mysql_101_seeding_transactiontype_games
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("GambaNet_Web.Domain.Entity.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("MaxBet")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("MinBet")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Game");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MaxBet = 1000m,
                            MinBet = 10m,
                            Name = "Casiino"
                        },
                        new
                        {
                            Id = 2,
                            MaxBet = 1000m,
                            MinBet = 10m,
                            Name = "Cassino roon"
                        });
                });

            modelBuilder.Entity("GambaNet_Web.Domain.Entity.TransactionType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("TransactionDescription")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("TransactionType");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            TransactionDescription = "Deposit"
                        },
                        new
                        {
                            Id = 2,
                            TransactionDescription = "Withdraw"
                        },
                        new
                        {
                            Id = 3,
                            TransactionDescription = "GameTransfer"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
