// <auto-generated />
using System;
using GambaNet_Web.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GambaNet_Web.Migrations
{
    [DbContext(typeof(GambaNetDbContext))]
    [Migration("20250113210123_AddQuotes")]
    partial class AddQuotes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("GambaNet.Domain.Entities.Quote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Quote");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "90 % gamblerů přestane hrát těsně před jejich další výhrou, nepřestávej!"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Kdo se nevzdá, vyhraje!"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Nezapomeň, že loseři prohrávájí - ale to ty nejsi, takže to nevzdávej!"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Kdo hraje, ten nezlobí!"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Rozdáváme peníze zdarma!"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Bez gamby nejsou koláče!"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Odvážným štěstí přeje!"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Není to tak moc o tom, co prohraješ - je to o tom co vyhraješ!"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Ty texty co tu vyskakujou nemají s psychologickou manipulací nic společného, to říkají slabí doktoři co nikdy nevyhráli pořádnou sumu!"
                        },
                        new
                        {
                            Id = 10,
                            Description = "Neznám nikoho, kdo by neměl rád peníze zdarma!"
                        },
                        new
                        {
                            Id = 11,
                            Description = "Rozlučte se s živořením!"
                        });
                });

            modelBuilder.Entity("GambaNet.Infrastructure.Identity.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ConcurrencyStamp = "00000000-0000-0000-0000-000000000000",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = 2,
                            ConcurrencyStamp = "00000000-0000-0000-0000-000000000000",
                            Name = "Default",
                            NormalizedName = "DEFAULT"
                        });
                });

            modelBuilder.Entity("GambaNet.Infrastructure.Identity.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<decimal?>("Balance")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("FirstName")
                        .HasColumnType("longtext");

                    b.Property<string>("LastName")
                        .HasColumnType("longtext");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccessFailedCount = 0,
                            Balance = 9999m,
                            ConcurrencyStamp = "b09a83ae-cfd3-4ee7-97e6-fbcf0b0fe78c",
                            Email = "admin@admin.cz",
                            EmailConfirmed = true,
                            FirstName = "Adminek",
                            LastName = "Adminovy",
                            LockoutEnabled = true,
                            NormalizedEmail = "ADMIN@ADMIN.CZ",
                            NormalizedUserName = "ADMIN",
                            PasswordHash = "AQAAAAEAACcQAAAAEM9O98Suoh2o2JOK1ZOJScgOfQ21odn/k6EYUpGWnrbevCaBFFXrNL7JZxHNczhh/w==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "SEJEPXC646ZBNCDYSM3H5FRK5RWP2TN6",
                            StartDate = new DateTime(2025, 1, 13, 22, 1, 20, 803, DateTimeKind.Local).AddTicks(471),
                            TwoFactorEnabled = false,
                            UserName = "admin"
                        },
                        new
                        {
                            Id = 2,
                            AccessFailedCount = 0,
                            Balance = 100m,
                            ConcurrencyStamp = "7a8d96fd-5918-441b-b800-cbafa99de97b",
                            Email = "manager@manager.cz",
                            EmailConfirmed = true,
                            FirstName = "Managerek",
                            LastName = "Managerovy",
                            LockoutEnabled = true,
                            NormalizedEmail = "MANAGER@MANAGER.CZ",
                            NormalizedUserName = "MANAGER",
                            PasswordHash = "AQAAAAEAACcQAAAAEOzeajp5etRMZn7TWj9lhDMJ2GSNTtljLWVIWivadWXNMz8hj6mZ9iDR+alfEUHEMQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "MAJXOSATJKOEM4YFF32Y5G2XPR5OFEL6",
                            StartDate = new DateTime(2025, 1, 13, 22, 1, 20, 803, DateTimeKind.Local).AddTicks(541),
                            TwoFactorEnabled = false,
                            UserName = "manager"
                        });
                });

            modelBuilder.Entity("GambaNet_Web.Domain.Entities.Ad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Url")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Ads", (string)null);
                });

            modelBuilder.Entity("GambaNet_Web.Domain.Entities.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BackgroundBlue")
                        .HasColumnType("int");

                    b.Property<int>("BackgroundGreen")
                        .HasColumnType("int");

                    b.Property<int>("BackgroundRed")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("GameType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ImagePath")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Winrate")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Game");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BackgroundBlue = 39,
                            BackgroundGreen = 179,
                            BackgroundRed = 230,
                            Description = "Máš na to ?",
                            GameType = "Cups",
                            Name = "Láska Strejdy",
                            Winrate = 100
                        },
                        new
                        {
                            Id = 2,
                            BackgroundBlue = 230,
                            BackgroundGreen = 80,
                            BackgroundRed = 39,
                            Description = "Kde to jen bylo",
                            GameType = "Slot",
                            Name = "Léto v Čečensku",
                            Winrate = 50
                        },
                        new
                        {
                            Id = 3,
                            BackgroundBlue = 169,
                            BackgroundGreen = 138,
                            BackgroundRed = 189,
                            Description = "Proč to musel udělat",
                            GameType = "Plinko",
                            Name = "Igor Hnízdo",
                            Winrate = 0
                        },
                        new
                        {
                            Id = 4,
                            BackgroundBlue = 58,
                            BackgroundGreen = 85,
                            BackgroundRed = 34,
                            Description = "Vyhraješ, nebo tě potopí?",
                            GameType = "Slot",
                            Name = "Hvězda Severu",
                            Winrate = 25
                        },
                        new
                        {
                            Id = 5,
                            BackgroundBlue = 255,
                            BackgroundGreen = 240,
                            BackgroundRed = 210,
                            Description = "Cítíš ten chlad?",
                            GameType = "Cups",
                            Name = "Zimní Vánek",
                            Winrate = 75
                        },
                        new
                        {
                            Id = 6,
                            BackgroundBlue = 40,
                            BackgroundGreen = 20,
                            BackgroundRed = 160,
                            Description = "Štěstí bolí.",
                            GameType = "Plinko",
                            Name = "Střepy Štěstí",
                            Winrate = 10
                        },
                        new
                        {
                            Id = 7,
                            BackgroundBlue = 50,
                            BackgroundGreen = 50,
                            BackgroundRed = 50,
                            Description = "Jsi připraven na bitvu?",
                            GameType = "Slot",
                            Name = "Rytířská Síla",
                            Winrate = 40
                        },
                        new
                        {
                            Id = 8,
                            BackgroundBlue = 0,
                            BackgroundGreen = 215,
                            BackgroundRed = 255,
                            Description = "Co ti přinese osud?",
                            GameType = "Cups",
                            Name = "Pohár Života",
                            Winrate = 60
                        },
                        new
                        {
                            Id = 9,
                            BackgroundBlue = 255,
                            BackgroundGreen = 100,
                            BackgroundRed = 100,
                            Description = "Co se mohlo stát jinak?",
                            GameType = "Slot",
                            Name = "Rozbité Sny",
                            Winrate = 20
                        },
                        new
                        {
                            Id = 10,
                            BackgroundBlue = 140,
                            BackgroundGreen = 180,
                            BackgroundRed = 210,
                            Description = "Zvládneš přežít?",
                            GameType = "Cups",
                            Name = "Pouštní Bouře",
                            Winrate = 30
                        },
                        new
                        {
                            Id = 11,
                            BackgroundBlue = 19,
                            BackgroundGreen = 69,
                            BackgroundRed = 139,
                            Description = "Zahřeje nebo spálí?",
                            GameType = "Plinko",
                            Name = "Horká Čokoláda",
                            Winrate = 45
                        },
                        new
                        {
                            Id = 12,
                            BackgroundBlue = 230,
                            BackgroundGreen = 216,
                            BackgroundRed = 173,
                            Description = "Zmrazíš soupeře?",
                            GameType = "Plinko",
                            Name = "Ledový Král",
                            Winrate = 55
                        },
                        new
                        {
                            Id = 13,
                            BackgroundBlue = 128,
                            BackgroundGreen = 0,
                            BackgroundRed = 128,
                            Description = "Najdeš poklad?",
                            GameType = "Slot",
                            Name = "Ztracené Město",
                            Winrate = 35
                        });
                });

            modelBuilder.Entity("GambaNet_Web.Domain.Entities.TransactionType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("TransactionDescription")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("TransactionType");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            TransactionDescription = "Deposit"
                        },
                        new
                        {
                            Id = 2,
                            TransactionDescription = "Withdraw"
                        },
                        new
                        {
                            Id = 3,
                            TransactionDescription = "GameTransfer"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("longtext");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            RoleId = 1
                        },
                        new
                        {
                            UserId = 1,
                            RoleId = 2
                        },
                        new
                        {
                            UserId = 2,
                            RoleId = 2
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("GambaNet.Infrastructure.Identity.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("GambaNet.Infrastructure.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("GambaNet.Infrastructure.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("GambaNet.Infrastructure.Identity.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GambaNet.Infrastructure.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("GambaNet.Infrastructure.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
