<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Views\NováSložka1\**" />
    <Content Remove="Views\NováSložka1\**" />
    <EmbeddedResource Remove="Views\NováSložka1\**" />
    <None Remove="Views\NováSložka1\**" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\GambaNet.Appliaction\GambaNet_Web.Application.csproj" />
    <ProjectReference Include="..\GambaNet_Web.Domain\GambaNet_Web.Domain.csproj" />
    <ProjectReference Include="..\GambaNet_Web.Infrastructure\GambaNet_Web.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Areas\Admin\Data\" />
    <Folder Include="Areas\Admin\Models\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="8.0.8" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.10">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="8.0.6" />
  </ItemGroup>

</Project>
